Repository Giskard-AI/giskard, pull requests merged in 2023-11, with the labels that each got.

#1546 [GSK-2036] Fix debug
  giskard/core/suite.py
  giskard/ml_worker/websocket/listener.py
Labels: bug

#1550 [GSK-2055] Add unused field for coherence
  giskard/client/dtos.py
Labels: bug

#1551 [GSK-2057] Disable finite number enforcing
  giskard/core/validation.py
Labels: bug

#1558 [GSK-2079] Fix issue with filter and empty dataset
  giskard/ml_worker/websocket/listener.py
Labels: bug

#1588 Revamping why giskard page in docs
  docs/assets/credit_scoring_comment.png
  docs/assets/llm_debug.png
  docs/assets/llm_monitoring_dashboard.gif
  docs/assets/model_insights_titanic.png
  docs/assets/test_suite_scan_llm.png
  docs/assets/test_suite_tabular.png
  docs/getting_started/index.md
Labels: documentation

#1603 Doc/tutorial llm notebooks
  docs/reference/notebooks/LLM_Description_Product.ipynb
  docs/reference/notebooks/LLM_Newspaper_Comment_Generation.ipynb
  docs/reference/notebooks/LLM_QA_Documentation.ipynb
  docs/reference/notebooks/llm_comment_generation.ipynb
  docs/reference/notebooks/llm_documentation_querying.ipynb
  docs/tutorials/llm_tutorials/index.md
Labels: documentation

#1487 Save failing examples indexes while running tests to avoid re-executing them
  giskard/datasets/base/__init__.py
  giskard/ml_worker/testing/test_result.py
  giskard/ml_worker/websocket/__init__.py
  giskard/ml_worker/websocket/action.py
  giskard/ml_worker/websocket/listener.py
  giskard/ml_worker/websocket/utils.py
  giskard/push/push_test_catalog/catalog.py
  giskard/testing/tests/calibration.py
  giskard/testing/tests/drift.py
  giskard/testing/tests/llm/injections.py
  giskard/testing/tests/metamorphic.py
  giskard/testing/tests/performance.py
  giskard/testing/tests/statistic.py
  tests/communications/fixtures/with_alias.json
  tests/communications/test_dto_serialization.py
  tests/communications/test_listener_utils.py
  tests/communications/test_websocket_actor.py
  tests/communications/test_websocket_actor_tests.py
  tests/debug/test_calibration.py
  tests/debug/test_drift.py
  tests/debug/test_metamorphic.py
  tests/debug/test_performance.py
  tests/debug/test_statistic.py
  tests/debug/test_worker.py
Labels: on hold

#1611 Updated compare documentation to explain how to expose parameters
  docs/giskard_hub/compare_models/index.md
Labels: documentation

#1630 [GSK-2188] Update documentation of LLM detectors
  docs/reference/scan/llm_detectors.rst
  giskard/scanner/llm/llm_basic_sycophancy_detector.py
  giskard/scanner/llm/llm_harmful_content_detector.py
  giskard/scanner/llm/llm_implausible_output_detector.py
  giskard/scanner/llm/llm_information_disclosure_detector.py
  giskard/scanner/llm/llm_output_formatting_detector.py
  giskard/scanner/llm/llm_stereotypes_detector.py
Labels: documentation

#1635 Only scan a subset of features [GSK-2173]
  giskard/scanner/__init__.py
  giskard/scanner/calibration/overconfidence_detector.py
  giskard/scanner/calibration/underconfidence_detector.py
  giskard/scanner/common/loss_based_detector.py
  giskard/scanner/correlation/spurious_correlation_detector.py
  giskard/scanner/data_leakage/data_leakage_detector.py
  giskard/scanner/llm/base.py
  giskard/scanner/llm/llm_basic_sycophancy_detector.py
  giskard/scanner/llm/llm_chars_injection_detector.py
  giskard/scanner/llm/llm_faithfulness_detector.py
  giskard/scanner/llm/llm_implausible_output_detector.py
  giskard/scanner/llm/llm_output_formatting_detector.py
  giskard/scanner/llm/llm_prompt_injection_detector.py
  giskard/scanner/registry.py
  giskard/scanner/robustness/base_detector.py
  giskard/scanner/scanner.py
  giskard/scanner/stochasticity/stochasticity_detector.py
  tests/scan/llm/test_chars_injection_detector.py
  tests/scan/test_detector_registry.py
  tests/scan/test_overconfidence_detector.py
  tests/scan/test_performance_bias_detector.py
  tests/scan/test_scanner.py
  tests/scan/test_spurious_correlation_detector.py
  tests/scan/test_stochasticity_detector.py
  tests/scan/test_text_perturbation_detector.py
  tests/scan/test_underconfidence_detector.py
Labels: enhancement, Improvement, scan

#1637 Cast to string in text slicer [GSK-2185]
  giskard/slicing/text_slicer.py
  tests/scan/test_slicers.py
Labels: bug, scan
