Repository Giskard-AI/giskard, pull requests merged in 2023-04, with the labels that each got.

#882 implemented automodel
  python-client/giskard/__init__.py
  python-client/giskard/core/dataset_validation.py
  python-client/giskard/core/model_validation.py
  python-client/giskard/datasets/__init__.py
  python-client/giskard/datasets/base/__init__.py
  python-client/giskard/ml_worker/core/model.py
  python-client/giskard/ml_worker/core/model_explanation.py
  python-client/giskard/ml_worker/core/suite.py
  python-client/giskard/ml_worker/server/ml_worker_service.py
  python-client/giskard/ml_worker/testing/drift_tests.py
  python-client/giskard/ml_worker/testing/metamorphic_tests.py
  python-client/giskard/ml_worker/testing/newtestlib/metamorphic/__init__.py
  python-client/giskard/ml_worker/testing/newtestlib/metamorphic/another_metamorphic_tests.py
  python-client/giskard/ml_worker/testing/newtestlib/metamorphic/metamorphic_tests.py
  python-client/giskard/ml_worker/testing/newtestlib/test.py
  python-client/giskard/ml_worker/testing/performance_tests.py
  python-client/giskard/ml_worker/testing/registry/lib.py
  python-client/giskard/ml_worker/testing/registry/registry.py
  python-client/giskard/ml_worker/testing/statistical_tests.py
  python-client/giskard/ml_worker/testing/tests/heuristic.py
  python-client/giskard/ml_worker/testing/tests/performance.py
  python-client/giskard/models/__init__.py
  python-client/giskard/models/base/__init__.py
  python-client/giskard/models/catboost/__init__.py
  python-client/giskard/models/huggingface/__init__.py
  python-client/giskard/models/pytorch/__init__.py
  python-client/giskard/models/sklearn/__init__.py
  python-client/giskard/models/tensorflow/__init__.py
  python-client/tests/fixtures/enron_multilabel_classification.py
  python-client/tests/fixtures/german_credit_scoring.py
  python-client/tests/fixtures/regression.py
  python-client/tests/test_custom_model.py
  python-client/tests/test_metamorphic_direction.py
  python-client/tests/test_model_auto_inference.py
  python-client/tests/test_model_explanation.py
  python-client/tests/test_programmatic.py
  python-client/tests/test_project_uploads.py
Labels: new-upload-api

#911 Implementing Webedia's user-test feedback (part 1)
  python-client/giskard/core/core.py
  python-client/giskard/core/model_validation.py
  python-client/giskard/core/validation.py
  python-client/giskard/datasets/__init__.py
  python-client/giskard/datasets/base/__init__.py
  python-client/giskard/ml_worker/testing/performance_tests.py
  python-client/giskard/ml_worker/testing/tests/performance.py
  python-client/giskard/models/__init__.py
  python-client/giskard/models/base/__init__.py
  python-client/giskard/models/catboost/__init__.py
  python-client/giskard/models/huggingface/__init__.py
  python-client/giskard/models/pytorch/__init__.py
  python-client/giskard/models/sklearn/__init__.py
  python-client/giskard/models/tensorflow/__init__.py
  python-client/tests/tensorflow/test_mnist.py
  python-client/tests/test_dataset.py
  python-client/tests/test_upload.py
Labels: High priority, user-test

#934 Added InternalTestFilter
  python-client/giskard/scanner/performance.py
  python-client/giskard/slicing/filters.py
Labels: safe for build

#926 [GSK-829] Increase debounce timeout in Inspector
  frontend/src/views/main/project/Inspector.vue
  frontend/src/views/main/project/PredictionExplanations.vue
  frontend/src/views/main/project/PredictionResults.vue
Labels: safe for build

#958 Remove `reset_index` from tests
  python-client/giskard/ml_worker/testing/tests/drift.py
  python-client/giskard/ml_worker/testing/tests/metamorphic.py
  python-client/giskard/ml_worker/testing/tests/performance.py
  python-client/giskard/ml_worker/testing/tests/statistic.py
  python-client/tests/testing/test_side_effects.py
Labels: safe for build

#965 task/gsk-980 validation inside dataset constructor, infer_column_types by default
  python-client/docs/guides/scan/index.md
  python-client/giskard/core/dataset_validation.py
  python-client/giskard/core/model_validation.py
  python-client/giskard/core/validation.py
  python-client/giskard/datasets/__init__.py
  python-client/giskard/datasets/base/__init__.py
  python-client/giskard/ml_worker/core/model_explanation.py
  python-client/giskard/ml_worker/server/ml_worker_service.py
  python-client/tests/fixtures/enron_multilabel_classification.py
  python-client/tests/fixtures/german_credit_scoring.py
  python-client/tests/fixtures/regression.py
  python-client/tests/pytorch/test_error.py
  python-client/tests/pytorch/test_linear_regression_pytorch_dataframe.py
  python-client/tests/test_dataset.py
  python-client/tests/test_project_uploads.py
  python-client/tests/test_statistical.py
  python-client/tests/test_upload.py
Labels: user-test

#962 [GSK-965] Task: Add turtles and change default green colour
  frontend/src/assets/logo_test_suite.png
  frontend/src/components/ApiTokenCard.vue
  frontend/src/plugins/vuetify.ts
  frontend/src/styles/global.scss
  frontend/src/views/main/Main.vue
  frontend/src/views/main/admin/InviteUsers.vue
  frontend/src/views/main/project/Models.vue
  frontend/src/views/main/project/ProjectsHome.vue
  frontend/src/views/main/project/TestSuite.vue
  frontend/src/views/main/project/TestSuiteExecutionOverview.vue
  frontend/src/views/main/project/TestSuiteExecutions.vue
  frontend/src/views/main/project/TestSuites.vue
  frontend/src/views/main/project/TestsCatalog.vue
Labels: safe for build

#937 Scan feature
  python-client/docs/guides/installation/index.md
  python-client/docs/guides/scan/index.md
  python-client/docs/guides/test-suite/index.md
  python-client/giskard/__init__.py
  python-client/giskard/datasets/base/__init__.py
  python-client/giskard/ml_worker/testing/tests/metamorphic.py
  python-client/giskard/ml_worker/testing/tests/performance.py
  python-client/giskard/ml_worker/testing/utils.py
  python-client/giskard/models/_precooked.py
  python-client/giskard/models/base/__init__.py
  python-client/giskard/scanner/__init__.py
  python-client/giskard/scanner/common.py
  python-client/giskard/scanner/issue.py
  python-client/giskard/scanner/performance.py
  python-client/giskard/scanner/templates/_issues_table.html
  python-client/giskard/scanner/templates/_main_content.html
  python-client/giskard/scanner/templates/_tab_header.html
  python-client/giskard/scanner/templates/base.html
  python-client/giskard/scanner/templates/scan_results.html
  python-client/giskard/scanner/visualization/__init__.py
  python-client/giskard/slicing/__init__.py
  python-client/giskard/slicing/base.py
  python-client/giskard/slicing/bruteforce_slicer.py
  python-client/giskard/slicing/category_slicer.py
  python-client/giskard/slicing/multiscale_slicer.py
  python-client/giskard/slicing/opt_slicer.py
  python-client/giskard/slicing/slice.py
  python-client/giskard/slicing/stop_words.py
  python-client/giskard/slicing/text_slicer.py
  python-client/giskard/slicing/tree_slicer.py
  python-client/giskard/slicing/utils.py
  python-client/pyproject.toml
  python-client/tests/models/test_precooked_model.py
  python-client/tests/scan/test_scan.py
  python-client/tests/test_performance.py
Labels: safe for build

#955 [GSK-959] Feature: Create a debugger tab
  backend/src/main/java/ai/giskard/domain/ml/Inspection.java
  backend/src/main/java/ai/giskard/repository/InspectionRepository.java
  backend/src/main/java/ai/giskard/service/InspectionService.java
  backend/src/main/java/ai/giskard/service/ModelService.java
  backend/src/main/java/ai/giskard/web/dto/InspectionCreateDTO.java
  backend/src/main/java/ai/giskard/web/dto/mapper/GiskardMapper.java
  backend/src/main/java/ai/giskard/web/dto/ml/InspectionDTO.java
  backend/src/main/java/ai/giskard/web/rest/controllers/InspectionController.java
  backend/src/main/resources/config/liquibase/changelog/20230419181155_changelog.xml
  backend/src/main/resources/config/liquibase/changelog/initial-v2.xml
  backend/src/main/resources/config/liquibase/master.xml
  frontend/src/api.ts
  frontend/src/assets/logo_debugger.png
  frontend/src/components/AddDebuggingSessionModal.vue
  frontend/src/generated-sources/ai/giskard/web/dto/inspection-create-dto.ts
  frontend/src/generated-sources/ai/giskard/web/dto/ml/inspection-dto.ts
  frontend/src/router.ts
  frontend/src/views/main/project/Debugger.vue
  frontend/src/views/main/project/InspectorLauncher.vue
  frontend/src/views/main/project/InspectorWrapper.vue
  frontend/src/views/main/project/Models.vue
  frontend/src/views/main/project/Project.vue
  python-client/giskard/ml_worker/server/ml_worker_service.py
Labels: safe for build
