Repository Giskard-AI/giskard, pull requests merged in 2023-12, with the labels that each got.

#1650 Fixed bug making it impossible to create giskard client
  giskard/client/giskard_client.py
Labels: bug, High priority

#1670 [GSK-2294] Fix doc for slicing and transformations
  giskard/core/core.py
  giskard/scanner/robustness/text_transformations.py
  giskard/slicing/slice.py
  giskard/slicing/text_slicer.py
Labels: bug

#1673 [GSK-2346] Avoid copying whole dataset when doing slicing
  giskard/datasets/base/__init__.py
Labels: bug

#1687 Implementation of the "PredictFromDatasetTool"
  giskard/llm/talk/config.py
  giskard/llm/talk/tools.py
  giskard/models/base/model.py
Labels: feature, Improvement

#1696 Feature/gsk 2336 query shap prediction explanation
  giskard/llm/talk/config.py
  giskard/llm/talk/tools.py
  giskard/models/base/model.py
Labels: enhancement, feature

#1702 Feature/gsk 2419 adapt workflow to the tools api
  giskard/llm/talk/config.py
  giskard/llm/talk/tools.py
  giskard/models/base/model.py
Labels: enhancement, feature
