Repository Giskard-AI/giskard, pull requests merged in 2023-05, with the labels that each got.

#1000 Improving the models module, introducing CloudPickleBasedModel
  python-client/giskard/__init__.py
  python-client/giskard/models/__init__.py
  python-client/giskard/models/base/__init__.py
  python-client/giskard/models/catboost/__init__.py
  python-client/giskard/models/huggingface/__init__.py
  python-client/giskard/models/pytorch/__init__.py
  python-client/giskard/models/sklearn/__init__.py
  python-client/giskard/models/tensorflow/__init__.py
  python-client/tests/huggingface/__init__.py
  python-client/tests/huggingface/test_email_classification_bert.py
  python-client/tests/huggingface/test_email_classification_bert_custom_model.py
  python-client/tests/pytorch/test_newspaper_classification_pytorch_custom_model.py
  python-client/tests/test_custom_model.py
Labels: new-upload-api, High priority

#1005 Feature/wrap prediction function
  python-client/docs/getting-started/scan/index.md
  python-client/docs/guides/index.rst
  python-client/docs/guides/installation/index.md
  python-client/docs/guides/tutorials/huggingface/BertForSequenceClassification_custom.md
  python-client/docs/guides/tutorials/pytorch/custom_model.md
  python-client/docs/index.md
  python-client/giskard/datasets/__init__.py
  python-client/giskard/models/__init__.py
  python-client/giskard/models/function/__init__.py
  python-client/tests/models/test_wrap_model.py
Labels: new-upload-api, High priority

#1004 Feature/Model for auto-serialization
  python-client/docs/getting-started/test-suite/index.md
  python-client/docs/guides/installation/index.md
  python-client/docs/reference/models/index.rst
  python-client/giskard/__init__.py
  python-client/giskard/models/automodel/__init__.py
  python-client/tests/automodel/test_automodel.py
  python-client/tests/automodel/test_infer_giskard_cls.py
  python-client/tests/fixtures/german_credit_scoring.py
  python-client/tests/huggingface/test_email_classification_bert_custom_model.py
  python-client/tests/pytorch/test_newspaper_classification_pytorch_custom_model.py
Labels: new-upload-api, High priority

#973 Robustness detections in giskard.scan
  python-client/giskard/commands/cli_server.py
  python-client/giskard/ml_worker/testing/registry/transformation_function.py
  python-client/giskard/ml_worker/testing/tests/metamorphic.py
  python-client/giskard/scanner/__init__.py
  python-client/giskard/scanner/issues.py
  python-client/giskard/scanner/logger.py
  python-client/giskard/scanner/performance/issues.py
  python-client/giskard/scanner/performance/model_bias_detector.py
  python-client/giskard/scanner/registry.py
  python-client/giskard/scanner/robustness/entity_swap.py
  python-client/giskard/scanner/robustness/french_gender_switch.py
  python-client/giskard/scanner/robustness/issues.py
  python-client/giskard/scanner/robustness/text_perturbation_detector.py
  python-client/giskard/scanner/robustness/text_transformations.py
  python-client/giskard/scanner/scanner.py
  python-client/giskard/scanner/templates/_main_content.html
  python-client/giskard/scanner/templates/_tab_header.html
  python-client/giskard/slicing/text_slicer.py
  python-client/pyproject.toml
  python-client/tests/scan/test_model_bias_detector.py
  python-client/tests/scan/test_robustness_scan.py
  python-client/tests/scan/test_scanner.py
  python-client/tests/scan/test_slicers.py
  python-client/tests/scan/test_text_transformations.py
Labels: High priority, scan

#1007 [GSK-1049] Update buttons related to Project component
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/fonts/RobotoMono-Italic-VariableFont_wght.ttf
  frontend/src/assets/fonts/RobotoMono-VariableFont_wght.ttf
  frontend/src/components/CodeSnippet.vue
  frontend/src/components/QuickStartStepper.vue
  frontend/src/router.ts
  frontend/src/stores/project-artifacts.ts
  frontend/src/views/main/Main.vue
  frontend/src/views/main/project/Catalog.vue
  frontend/src/views/main/project/Datasets.vue
  frontend/src/views/main/project/Models.vue
  frontend/src/views/main/project/Project.vue
  frontend/src/views/main/project/ProjectProperties.vue
  frontend/src/views/main/project/ProjectsHome.vue
Labels: Improvement

#1027 GSK-935 Support regression models in scan
  python-client/giskard/models/_precooked.py
  python-client/giskard/scanner/performance/issues.py
  python-client/giskard/scanner/performance/performance_bias_detector.py
  python-client/giskard/scanner/result.py
  python-client/giskard/scanner/templates/_issues/performance.html
  python-client/giskard/scanner/visualization/custom_jinja.py
Labels: on hold, Launch

#1039 [GSK-1061] Catalog tab: UI improvements
  frontend/src/api.ts
  frontend/src/components/CodeSnippet.vue
  frontend/src/components/SuiteInputListSelector.vue
  frontend/src/router.ts
  frontend/src/views/main/Main.vue
  frontend/src/views/main/project/Catalog.vue
  frontend/src/views/main/project/Datasets.vue
  frontend/src/views/main/project/FiltersCatalog.vue
  frontend/src/views/main/project/Models.vue
  frontend/src/views/main/project/TestsCatalog.vue
  frontend/src/views/main/project/TransformationsCatalog.vue
  frontend/src/views/main/project/modals/AddTestToSuite.vue
  frontend/src/views/main/project/modals/UploadArtifactModal.vue
  frontend/src/views/main/utils/DatasetColumnSelector.vue
  frontend/src/views/main/utils/KwargsCodeEditor.vue
  frontend/src/views/main/utils/ModelSelector.vue
  frontend/src/views/main/utils/SlicingFunctionSelector.vue
Labels: Launch

#1014 GSK-1035 Add language detection in scan
  python-client/giskard/datasets/metadata/text_metadata_provider.py
  python-client/giskard/scanner/robustness/entity_swap.py
  python-client/giskard/scanner/robustness/french_gender_switch.py
  python-client/giskard/scanner/robustness/nationalities.json
  python-client/giskard/scanner/robustness/text_transformations.py
  python-client/pdm.lock
  python-client/pyproject.toml
  python-client/tests/datasets/test_metadata.py
  python-client/tests/scan/test_text_transformations.py
Labels: safe for build, Launch

#1038 Hide threshold for non-binary classification models
  frontend/src/views/main/project/PredictionResults.vue
Labels: Launch

#1029 GSK-841 Adding names to tests exported from scan
  python-client/giskard/scanner/performance/issues.py
  python-client/giskard/scanner/result.py
  python-client/giskard/scanner/robustness/issues.py
Labels: Launch

#1049 fixed warning issue
  python-client/giskard/models/base/__init__.py
  python-client/giskard/models/utils.py
Labels: Launch

#1045 task/implemented escapechar
  python-client/giskard/client/io_utils.py
Labels: Launch

#1044 Task/removed duplicate tests
  python-client/giskard/testing/__init__.py
  python-client/giskard/testing/tests/performance.py
  python-client/tests/test_performance.py
Labels: Launch

#1042 Task/inverted classification labels validation
  python-client/giskard/core/model_validation.py
  python-client/tests/test_upload.py
Labels: Launch

#1041 error if classification_labels is needed but not provided
  python-client/giskard/models/base/__init__.py
  python-client/tests/test_model_auto_inference.py
Labels: Launch
