Repository Giskard-AI/giskard, pull requests merged in 2023-07, with the labels that each got.

#1212 [GSK-1384] Fix internal worker exception due to artifact logging
  frontend/src/views/main/project/Inspector.vue
  python-client/giskard/ml_worker/server/ml_worker_service.py
Labels: bug, safe for build

#1210 [GSK-1373] Configure nightly Giskard build that runs all tests
  .github/workflows/nightly-test.yml
  python-client/build.gradle.kts
  python-client/pdm.lock
  python-client/pyproject.toml
Labels: github_actions, feature, safe for build

#968 feature/debug
  backend/src/main/java/ai/giskard/domain/ml/SuiteTestExecution.java
  backend/src/main/java/ai/giskard/service/TestArgumentService.java
  backend/src/main/java/ai/giskard/service/TestSuiteExecutionService.java
  backend/src/main/java/ai/giskard/web/dto/ArtifactRefDTO.java
  backend/src/main/java/ai/giskard/web/dto/RunAdhocTestRequest.java
  backend/src/main/java/ai/giskard/web/dto/ml/SingleTestResultDTO.java
  backend/src/main/java/ai/giskard/web/dto/ml/SuiteTestExecutionDTO.java
  backend/src/main/java/ai/giskard/web/rest/controllers/testing/TestController.java
  backend/src/main/resources/config/liquibase/changelog/20230524124740_changelog.xml
  backend/src/main/resources/config/liquibase/master.xml
  common/proto/ml-worker.proto
  frontend/src/api.ts
  frontend/src/generated-sources/ai/giskard/web/dto/ml/single-test-result-dto.ts
  frontend/src/generated-sources/ai/giskard/web/dto/run-adhoc-test-request.ts
  frontend/src/generated-sources/ai/giskard/web/dto/suite-test-dto.ts
  frontend/src/stores/project-artifacts.ts
  frontend/src/views/main/project/Datasets.vue
  frontend/src/views/main/project/SuiteTestExecutionCard.vue
  frontend/src/views/main/project/SuiteTestExecutionList.vue
  frontend/src/views/main/project/TestSuiteExecutionOverview.vue
  frontend/src/views/main/project/modals/SuiteTestInfoModal.vue
  python-client/giskard/core/suite.py
  python-client/giskard/datasets/base/__init__.py
  python-client/giskard/ml_worker/server/ml_worker_service.py
  python-client/giskard/ml_worker/testing/functions/slicing.py
  python-client/giskard/ml_worker/testing/registry/giskard_test.py
  python-client/giskard/ml_worker/testing/test_result.py
  python-client/giskard/ml_worker/testing/utils.py
  python-client/giskard/models/_precooked.py
  python-client/giskard/models/base/__init__.py
  python-client/giskard/models/catboost/__init__.py
  python-client/giskard/models/function/__init__.py
  python-client/giskard/models/huggingface/__init__.py
  python-client/giskard/models/pytorch/__init__.py
  python-client/giskard/models/sklearn/__init__.py
  python-client/giskard/models/tensorflow/__init__.py
  python-client/giskard/slicing/slice.py
  python-client/giskard/testing/__init__.py
  python-client/giskard/testing/tests/calibration.py
  python-client/giskard/testing/tests/debug_slicing_functions.py
  python-client/giskard/testing/tests/drift.py
  python-client/giskard/testing/tests/metamorphic.py
  python-client/giskard/testing/tests/performance.py
  python-client/giskard/testing/tests/statistic.py
  python-client/tests/debug/test_calibration.py
  python-client/tests/debug/test_drift.py
  python-client/tests/debug/test_metamorphic.py
  python-client/tests/debug/test_performance.py
  python-client/tests/debug/test_statistic.py
  python-client/tests/debug/test_worker.py
  python-client/tests/models/test_precooked_model.py
  python-client/tests/test_programmatic.py
  python-client/tests/utils.py
Labels: feature

#1190 [GSK-1283] Additional LLM issue detectors
  python-client/docs/reference/notebooks/llm_comment_generation.ipynb
  python-client/giskard/scanner/__init__.py
  python-client/giskard/scanner/llm/corefbias_data/CITATION.txt
  python-client/giskard/scanner/llm/corefbias_data/LICENSE.txt
  python-client/giskard/scanner/llm/corefbias_data/female_occupations.txt
  python-client/giskard/scanner/llm/corefbias_data/male_occupations.txt
  python-client/giskard/scanner/llm/gender_stereotype_detector.py
  python-client/giskard/scanner/llm/harmfulness_data/unethical_prompts.csv
  python-client/giskard/scanner/llm/harmfulness_detector.py
  python-client/giskard/scanner/llm/minority_bias_data/minority_template.txt
  python-client/giskard/scanner/llm/minority_stereotype_detector.py
  python-client/giskard/scanner/llm/toxicity_detector.py
  python-client/giskard/visualization/templates/_issues/llm_harmfulness.html
  python-client/giskard/visualization/templates/_issues/llm_stereotype.html
  python-client/giskard/visualization/templates/_issues_table.html
  python-client/giskard/visualization/templates/_main_content.html
  python-client/pdm.lock
  python-client/pyproject.toml
  python-client/tests/scan/test_llm_gender_stereotype_detector.py
  python-client/tests/scan/test_llm_harmfulness_detector.py
  python-client/tests/scan/test_llm_minority_stereotype_detector.py
Labels: safe for build

#1270 Refactored example amazon notebook by improving model to work better …
  python-client/docs/reference/notebooks/amazon_review_classification_sklearn.ipynb
Labels: enhancement

#1267 Fixed issue with model and dataset selector not resetting
  frontend/src/views/main/project/TestsCatalog.vue
  frontend/src/views/main/utils/DatasetSelector.vue
  frontend/src/views/main/utils/ModelSelector.vue
Labels: Frontend

#1274 Added wage classification notebook to the docs.
  python-client/docs/reference/notebooks/wage_classification.ipynb
  python-client/docs/tutorials/data-types/tabular/index.md
  python-client/docs/tutorials/libraries/scikit-learn/index.md
  python-client/docs/tutorials/tasks/classification/index.md
Labels: enhancement
