Repository Giskard-AI/giskard, pull requests merged in 2024-01, with the labels that each got.

#1722 Feature/gsk 2337 query prediction for the row from the user input
  giskard/llm/talk/config.py
  giskard/llm/talk/tools.py
  giskard/models/base/model.py
Labels: enhancement, feature

#1729 Feature/gsk 2421 history persistence between the talk calls
  giskard/llm/talk/config.py
  giskard/models/base/model.py
  giskard/models/talk_result.py
Labels: enhancement, feature

#1704 Docs: replace space duplication instructions by docker template creation instructions
  docs/assets/integrations/hfs/create_from_template.png
  docs/assets/integrations/hfs/create_new_space.png
  docs/giskard_hub/installation_hub/install_hfs/index.md
  docs/integrations/huggingface/index.md
Labels: documentation

#1615 [GSK-2280] Feature: Added Number-to-Words Transformation
  giskard/scanner/robustness/text_perturbation_detector.py
  giskard/scanner/robustness/text_transformations.py
  pdm.lock
  pyproject.toml
  tests/scan/test_text_transformations.py
Labels: enhancement, safe for build
